# Asterisk source: https://github.com/asterisk/asterisk/archive/14.2.0.tar.gz

name: asterisk # you probably want to 'snapcraft register <name>'
version: '14.0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Asterisk # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    asterisk:
        command: astlaunch.sh
        daemon:  simple
        plugs:
            -   network
            -   network-bind
    rasterisk:
        command:    sbin/rasterisk
        plugs:
            -   network

parts:
  asterisk:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/asterisk/asterisk/archive/14.2.0.tar.gz
    build-packages:
        -   gcc
        -   g++
        -   build-essential
        -   libncurses5-dev
        -   uuid-dev
        -   libcap2
        -   libedit2
        -   libjansson4
        -   libjansson-dev
        -   libpopt0
        -   libsqlite3-0
        -   libsqlite3-dev
        -   libssl1.0.0
        -   libuuid1
        -   libxml2
        -   libxslt1.1
        -   init-system-helpers
        -   libxml2-dev

  configfile:
    plugin: copy
    source: hacks/
    files:
        'configfile': ./
        
  launcher:
    plugin: copy
    source: hacks/
    files:
        'astlaunch.sh': ./
